name: upload_and_save
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0
dependencies:
  skynet:
    git: 
      url: https://github.com/redsolver/skynet.git
      ref: experimental

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
